import type { MediaItem } from '@/lib/types';

export const mediaData: MediaItem[] = [
  {
    id: 1,
    title: 'Cosmic Odyssey',
    overview: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.',
    poster_path: 'https://picsum.photos/500/750?random=1',
    backdrop_path: 'https://picsum.photos/1280/720?random=1',
    release_date: '2014-11-05',
    vote_average: 8.6,
    genres: ['Sci-Fi', 'Drama', 'Adventure'],
    media_type: 'movie',
  },
  {
    id: 2,
    title: 'The Shadow Realm',
    overview: 'A private detective uncovers a conspiracy while investigating a brutal murder in a city of perpetual night.',
    poster_path: 'https://picsum.photos/500/750?random=2',
    backdrop_path: 'https://picsum.photos/1280/720?random=2',
    release_date: '2022-03-04',
    vote_average: 7.9,
    genres: ['Crime', 'Noir', 'Thriller'],
    media_type: 'movie',
  },
  {
    id: 3,
    title: 'Echoes of Eternity',
    overview: 'A historian discovers a way to communicate with the past, but her actions have unforeseen consequences on the present.',
    poster_path: 'https://picsum.photos/500/750?random=3',
    backdrop_path: 'https://picsum.photos/1280/720?random=3',
    release_date: '2019-07-12',
    vote_average: 7.5,
    genres: ['Drama', 'Fantasy', 'History'],
    media_type: 'tv',
  },
  {
    id: 4,
    title: 'Cybernetic Revolution',
    overview: 'In a dystopian future, a group of rebels fight against an oppressive AI that controls every aspect of society.',
    poster_path: 'https://picsum.photos/500/750?random=4',
    backdrop_path: 'https://picsum.photos/1280/720?random=4',
    release_date: '2023-01-20',
    vote_average: 8.9,
    genres: ['Action', 'Sci-Fi', 'Dystopian'],
    media_type: 'tv',
  },
  {
    id: 5,
    title: 'The Last Alchemist',
    overview: 'A brilliant but disgraced scientist tries to redeem himself by solving the one puzzle that eluded him: eternal life.',
    poster_path: 'https://picsum.photos/500/750?random=5',
    backdrop_path: 'https://picsum.photos/1280/720?random=5',
    release_date: '2018-09-21',
    vote_average: 8.1,
    genres: ['Mystery', 'Thriller', 'Sci-Fi'],
    media_type: 'movie',
  },
  {
    id: 6,
    title: 'Sunken Kingdom',
    overview: 'A marine biologist stumbles upon a lost underwater civilization, but its inhabitants are not what they seem.',
    poster_path: 'https://picsum.photos/500/750?random=6',
    backdrop_path: 'https://picsum.photos/1280/720?random=6',
    release_date: '2021-05-14',
    vote_average: 6.8,
    genres: ['Adventure', 'Fantasy', 'Horror'],
    media_type: 'movie',
  },
  {
    id: 7,
    title: 'Chronos',
    overview: 'A series of interconnected stories showing how time affects different people across centuries.',
    poster_path: 'https://picsum.photos/500/750?random=7',
    backdrop_path: 'https://picsum.photos/1280/720?random=7',
    release_date: '2020-11-01',
    vote_average: 9.1,
    genres: ['Drama', 'Anthology'],
    media_type: 'tv',
  },
  {
    id: 8,
    title: 'The Gilded Cage',
    overview: 'The lives of the ultra-rich take a dark turn when one of their own is murdered during a lavish party.',
    poster_path: 'https://picsum.photos/500/750?random=8',
    backdrop_path: 'https://picsum.photos/1280/720?random=8',
    release_date: '2024-02-16',
    vote_average: 8.3,
    genres: ['Crime', 'Drama', 'Mystery'],
    media_type: 'tv',
  },
    {
    id: 9,
    title: 'Nomad\'s Land',
    overview: 'After an economic collapse, a woman embarks on a journey through the American West, living as a van-dwelling modern-day nomad.',
    poster_path: 'https://picsum.photos/500/750?random=9',
    backdrop_path: 'https://picsum.photos/1280/720?random=9',
    release_date: '2020-09-11',
    vote_average: 7.4,
    genres: ['Drama'],
    media_type: 'movie',
  },
  {
    id: 10,
    title: 'Arcane Warriors',
    overview: 'In a world where magic is outlawed, a young mage discovers her powers and joins a rebellion to restore magic to the kingdom.',
    poster_path: 'https://picsum.photos/500/750?random=10',
    backdrop_path: 'https://picsum.photos/1280/720?random=10',
    release_date: '2023-08-18',
    vote_average: 8.7,
    genres: ['Fantasy', 'Adventure', 'Action'],
    media_type: 'tv',
  },
  {
    id: 11,
    title: 'Quantum Entanglement',
    overview: 'A romantic comedy about two physicists who fall in love while proving that their particles are cosmically linked.',
    poster_path: 'https://picsum.photos/500/750?random=11',
    backdrop_path: 'https://picsum.photos/1280/720?random=11',
    release_date: '2019-02-14',
    vote_average: 7.2,
    genres: ['Romance', 'Comedy', 'Sci-Fi'],
    media_type: 'movie',
  },
  {
    id: 12,
    title: 'The Verdant Planet',
    overview: 'A documentary series exploring the most remote and untouched ecosystems on Earth, revealing the secret lives of its inhabitants.',
    poster_path: 'https://picsum.photos/500/750?random=12',
    backdrop_path: 'https://picsum.photos/1280/720?random=12',
    release_date: '2022-04-22',
    vote_average: 9.5,
    genres: ['Documentary', 'Nature'],
    media_type: 'tv',
  },
];
